sudo: false
language: python
python:
  - "pypy"
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
cache:
  directories: 
  - $HOME/.pip-cache
# command to run tests

script:
  - pip install -r requirements-travis.txt --download-cache $HOME/.pip-cache
  - make travis
after_success: make coveralls
notifications:
  email:
    - paultag@gmail.com
  irc:
    channels:
      - "irc.freenode.net#woo-city-commits"
      - "irc.freenode.net#hy"
    on_success: change
    on_failure: change
    use_notice: false
